PRODUCT_PACKAGES += \
	HardwareOverlayPicker \
	QtiAudio \
	TrebleApp \
	treble-overlay-NavBar \
	treble-overlay-NightMode \
	treble-overlay-SystemUI-FalseLocks \
	treble-overlay-Telephony-LTE \
	treble-overlay-caf-ims \
	treble-overlay-devinputjack \
	treble-overlay-duoqin-qin2pro \
	treble-overlay-gestures \
	treble-overlay-huawei \
	treble-overlay-huawei-ANE \
	treble-overlay-huawei-ARE \
	treble-overlay-huawei-ATU \
	treble-overlay-huawei-AUM \
	treble-overlay-huawei-BKL \
	treble-overlay-huawei-BND \
	treble-overlay-huawei-CLT \
	treble-overlay-huawei-DUK \
	treble-overlay-huawei-EML \
	treble-overlay-huawei-LLD \
	treble-overlay-huawei-PIC \
	treble-overlay-huawei-PRA \
	treble-overlay-huawei-RNE \
	treble-overlay-huawei-STF \
	treble-overlay-huawei-VTR \
	treble-overlay-huawei-EVA \
	treble-overlay-huawei-WAS \
	treble-overlay-hw-ims \
	treble-overlay-misc-dt2w \
	treble-overlay-mtk-ims \
	treble-overlay-sec-ims \
	treble-overlay-sprd-ims \
	treble-overlay-telephony-caf-ims \
	treble-overlay-telephony-mtk-ims \
	treble-overlay-telephony-slsi-ims \
	treble-overlay-tethering \
	treble-overlay-umidigi-power \
	treble-overlay-webview \
	treble-overlay-wifi5g
